name: Case Test
on:
  push:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

jobs:
  testAllModesLikeInTheReadme:
    name: Test in ${{ matrix.testMode }} of version ${{ matrix.unityVersion }} on ${{ matrix.baseRunner }}
    runs-on: ${{ matrix.baseRunner }}
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        baseRunner:
          - windows-latest
          - ubuntu-latest
        projectPath:
          - unity-project-with-correct-tests
        unityVersion:
          - 2022.3.13f1
        testMode:
          - standalone
    steps:
      ###########################
      #         Checkout        #
      ###########################
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      ###########################
      #          Cache          #
      ###########################
      - uses: actions/cache@v3
        with:
          path: ${{ matrix.projectPath }}/Library
          key: Library-${{ matrix.baseRunner }}-${{ matrix.projectPath }}
          restore-keys: |
            Library-${{ matrix.baseRunner }}
      - uses: ./
        id: tests
        timeout-minutes: 60
        with:
          projectPath: ${{ matrix.projectPath }}
          unityVersion: ${{ matrix.unityVersion }}
          testMode: ${{ matrix.testMode }}
          artifactsPath: ${{ matrix.baseRunner }}-${{ matrix.testMode }}-artifacts
      - uses: actions/upload-artifact@v3
        with:
          name: Test results for ${{ matrix.testMode }}
          path: ${{ steps.tests.outputs.artifactsPath }}
          retention-days: 14
